fos_rest:
    exception:
        exception_controller: 'app.json_exception_controller:showAction'
        codes:
            'Symfony\Component\Routing\Exception\ResourceNotFoundException': 404
            'Symfony\Component\OptionsResolver\Exception\InvalidOptionsException': 400
    param_fetcher_listener: true
    body_listener: true
    format_listener: true
    view:
        empty_content: 204
        view_response_listener: 'force'
        formats:
            json : true
        failed_validation: HTTP_BAD_REQUEST
    routing_loader:
        default_format: json
        include_format: false
