nelmio_api_doc:
    documentation:
        info:
            title: Promote Api
            description: Handsome API to work with an artist roster
            version: 1.0.0
        produces:
          - application/json
        consumes:
          - application/json
