# Virtual FileSystem on S3
oneup_flysystem:
    adapters:
        app.flysystem_adapter:
            awss3v3:
                client: app.s3_client
                bucket: "%env(AWS_BUCKET)%"
                prefix: ~
                options:
                    ACL: public-read

    filesystems:
        awss3_fs:
            adapter: app.flysystem_adapter
            mount: awss3_fs
