vich_uploader:
    db_driver: orm
    storage: flysystem
    mappings:
        artist_image:
            upload_destination: awss3_fs
            namer: vich_uploader.namer_uniqid
            inject_on_load:     false
            delete_on_update:   true
            delete_on_remove:   true
