<?php

namespace AppBundle\Repository;

/**
 * LabelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LabelRepository extends RestEntityRepository
{
}
