app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /
    defaults: {_format: json}

artists:
    type:     rest
    resource: AppBundle\Controller\ArtistController

labels:
    type:     rest
    resource: AppBundle\Controller\LabelController
