app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /
    defaults: {_format: json}

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc

artists:
    type:     rest
    resource: AppBundle\Controller\ArtistController

labels:
    type:     rest
    resource: AppBundle\Controller\LabelController

gigs:
    type:     rest
    resource: AppBundle\Controller\GigController
