# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    #Authenticators
    app.token_authenticator:
        class: AppBundle\Security\TokenAuthenticator
        arguments: ['@doctrine.orm.entity_manager']
    app.form_authenticator:
        class: AppBundle\Security\FormAuthenticator
        arguments: ['@security.password_encoder']

    #Voters
    app.post_voter:
        class: AppBundle\Security\Voter\ArtistVoter
        arguments: ['@security.access.decision_manager']
        public: false
        tags:
            - { name: security.voter }

    app.relation_provider_resolver.artist:
        class: AppBundle\Hateoas\RelationProviderResolver\ArtistRelationProviderResolver
        tags:
            - { name: hateoas.relation_provider }
