services:
    bigz_halapi.relation_factory:
        class: bigz\halapi\Factory\RelationFactory
        arguments: ["@router", "@annotation_reader", "@doctrine.orm.entity_manager"]

    bigz_halapi.pagination_factory:
        class: bigz\halapi\Factory\PaginationFactory
        arguments: ["@router", "@doctrine.orm.entity_manager"]

    bigz_halapi.json_event_subscriber:
        class: bigz\halapi\Subscriber\JsonEventSubscriber
        arguments: ["@bigz_halapi.relation_factory"]
        tags:
            - { name: jms_serializer.event_subscriber }
