services:
    bigz_halapi.links_relation:
        class: bigz\halapi\Relation\LinksRelation
        arguments: ["@router", "@annotation_reader", "@doctrine.orm.entity_manager", "@request_stack"]
    bigz_halapi.embedded_relation:
        class: bigz\halapi\Relation\EmbeddedRelation
        arguments: ["@router", "@annotation_reader", "@doctrine.orm.entity_manager", "@request_stack"]

    bigz_halapi.relation_factory:
        class: bigz\halapi\Factory\RelationFactory
        arguments: [["@bigz_halapi.embedded_relation", "@bigz_halapi.links_relation"]]

    bigz_halapi.pagination_factory:
        class: bigz\halapi\Factory\PaginationFactory
        arguments: ["@router", "@doctrine.orm.entity_manager", "@request_stack"]

    bigz_halapi.json_event_subscriber:
        class: bigz\halapi\Subscriber\JsonEventSubscriber
        arguments: ["@bigz_halapi.relation_factory"]
        tags:
            - { name: jms_serializer.event_subscriber }
