artists:
    type:     rest
    resource: App\Controller\ArtistController

labels:
    type:     rest
    resource: App\Controller\LabelController

gigs:
    type:     rest
    resource: App\Controller\GigController

token:
    type:     rest
    resource: App\Controller\TokenController

